### PR TITLE
feat: prepare the first lecture

### PR DESCRIPTION
**Pull request by honzaMaly**
## :memo: Changelog

- [x] Intro Lecture Page -> program, motivation, goals
- [x] Motivational Example Covering/Teasing/Introducing Topics
- [x] Basics of Python - examples & exercises

## :link: Links

- #7

### CODE REVIEW

**Review by jardabezdek — COMMENTED** [review]
@honzaMaly, in my opinion it looks really good! 💪 I have just a few pointers.

- In the [development `README.md` file, in the last section](https://github.com/strvcom/ds-academy/tree/feat/first_lecture/development#publish-handbook-to-github-pages), there is written the following:  "Vist the [project's GitHub Page](https://strvcom.github.io/ds-academy/intro.html) to see final results." Besides the fact, there is a typo in the very first word, the bigger problem is that the Github Page link isn't working.
- Maybe, it would be good idea to write github action script that would publish handbook to GitHub Pages every time you push code to `master` branch, so you don't have to do that manually.
- Please, unify using `'` and `"` in your python code. Do not use both. I prefer using double quotes, especially because of the reasons named in this [Łukasz Langa's speach](https://youtu.be/esZLCuWs_2Y?t=1382), but it is up to you.
- I would also suggest using the same style of string formatting. Once you are using f-strings: `print(f"index {n}, value {i}")`, then you are using multiple `print` function arguments: `print("index ", n, ", value ", i)`. Personally, I would pick f-string and use only that style of string formatting.

**Comment by niekstrv** [comment]
@honzaMaly 

- The link to loading and chercking data is somehow not working: We have been working with cleaned data in these exercises. One way to make it more challenging is to uncomment one of lines in the [Loading and Checking Data](https://github.com/strvcom/ds-academy/blob/0e1aad62b3aa3ab10a1ee7e045efe430883ee5c4/lectures/01_lecture/#loading-and-checking-data). 
- Add a link to random forest (sk-learn)
- I am not completely convinced that the second exercise is right for the first lecture. I think that this question is pretty advanced and not on the right level for the first lecture. I would do something like this: replace missing values with the algorithm of page X (insert url) or standardize the values with algorithm of page Y (insert url). 
- Another idea for a question would be to adjust the grid search in order to take on the parameters for a random forest?

**Comment by lukoucky** [comment]
@honzaMaly 
Great work! You really put the bar high for the rest of us :+1:

For the python basics:
I would add some info and live coding examples about the numbers and strings, include some info about importing modules and show interpreter mode in the terminal.
Also, it would be great to show something about classic first python mistakes. First what comes to my mind is a lot of problems that came from the difference between references to numbers vs. lists or dicts. Like this:
```python
>>> a = [1,2,3]
>>> b = a
>>> a[1] = 'ahoj'
>>> print(b)
[1, 'ahoj', 3]
```
A lot of mistakes came from the fact that `b` is here just a reference to `a` and changing anything in list `a` will change list `b`. But in similar example with numbers you get the copy of the first number and you can change `a` without changing `b`.
```python
>>> a = 1
>>> b = a
>>> a = 1254
>>> print(b)
1
```

For the motivational example:
I think it's great! 
I would keep the homework as it is. As @niekstrv said, it is true that the second HW is more difficult but I would keep it in and go even further and include the third much, much harder HW.
People that have some experience and want to work on HW will have some challenges and we can show them at the beginning of the next lecture how to solve even more difficult problems. People that are not that advanced still have first simple HW.
Also from the experience in iOS academy - there are about 20 of us and only 3 - 5 work on homeworks :smile:

**Review by niekstrv — APPROVED** [review]

**Comment by honzaMaly** [comment]
> @honzaMaly, in my opinion it looks really good! 💪 I have just a few pointers.
> 
> * In the [development `README.md` file, in the last section](https://github.com/strvcom/ds-academy/tree/feat/first_lecture/development#publish-handbook-to-github-pages), there is written the following:  "Vist the [project's GitHub Page](https://strvcom.github.io/ds-academy/intro.html) to see final results." Besides the fact, there is a typo in the very first word, the bigger problem is that the Github Page link isn't working.
> * Maybe, it would be good idea to write github action script that would publish handbook to GitHub Pages every time you push code to `master` branch, so you don't have to do that manually.
> * Please, unify using `'` and `"` in your python code. Do not use both. I prefer using double quotes, especially because of the reasons named in this [Łukasz Langa's speach](https://youtu.be/esZLCuWs_2Y?t=1382), but it is up to you.
> * I would also suggest using the same style of string formatting. Once you are using f-strings: `print(f"index {n}, value {i}")`, then you are using multiple `print` function arguments: `print("index ", n, ", value ", i)`. Personally, I would pick f-string and use only that style of string formatting.

Thanks - I will fix and unify it :)

**Comment by honzaMaly** [comment]
> @honzaMaly
> 
> * The link to loading and chercking data is somehow not working: We have been working with cleaned data in these exercises. One way to make it more challenging is to uncomment one of lines in the [Loading and Checking Data](https://github.com/strvcom/ds-academy/blob/0e1aad62b3aa3ab10a1ee7e045efe430883ee5c4/lectures/01_lecture/#loading-and-checking-data).
> * Add a link to random forest (sk-learn)
> * I am not completely convinced that the second exercise is right for the first lecture. I think that this question is pretty advanced and not on the right level for the first lecture. I would do something like this: replace missing values with the algorithm of page X (insert url) or standardize the values with algorithm of page Y (insert url).
> * Another idea for a question would be to adjust the grid search in order to take on the parameters for a random forest?

Thanks! The link works in the handbook. I will keep exercises as is - we can adjust as we go :)

**Comment by honzaMaly** [comment]
> ```python
> a = [1,2,3]
> >>> b = a
> >>> a[1] = 'ahoj'
> >>> print(b)
> [1, 'ahoj', 3]
> ```

Thanks! I will incorporate your suggestions on mistakes. Plus, I will add a reference on modules and classes :) I will keep exercises as is - we can adjust as we go :) I made a note to make a guide on "Python in terminal" - let's have it in the Getting Started section :)

**Pull request merged**
