### PR TITLE
Feat/fifth_lecture

### PR DESCRIPTION
**Pull request by lukoucky**
## :memo: Changelog

The Fifth lecture: Evaluating, comparing, and selecting ML models
- [X] ~~Motivational example notebook~~ Removed - there are plenty of examples in the other two notebooks
- [X] Model evaluation notebook
- [x] Model selection notebook 

## :link: Links

- #20

## :white_check_mark: Checklist

- [x] All notebooks are in with desired content
- [x] All text is spell checked & fact-checked
- [x] All files for the Jupyter book are in

## ❓ Questions for reviewers

* `lectures/05_lecture/model_evaluation.ipynb`: In the Binary classifier example is used the artificial output of the nonexisting classifier using two distributions. Not sure if this would be confusing or not? Should I rather use real model and real outputs? I really like current implementations because I can change one parameter and immediately have new distribution and show how it changes evaluation metrics and what it can say about the data but it can be somehow confusing for students not to see the output generated by model. What do you think?

### CODE REVIEW

**Comment by niekstrv** [comment]
@lukoucky will you also touch cross-validation?

**Comment by lukoucky** [comment]
> 

@niekstrv  Yes, planning it in `Model selection notebook` part

**Review by jardabezdek — APPROVED** [review]
I didn't have much time to check it properly, so I just quickly went through. 😢 However, it looks really sharp! 💪 The only thing I am missing is exercise for our students.

**Comment by lukoucky** [comment]
> I didn't have much time to check it properly, so I just quickly went through. 😢 However, it looks really sharp! 💪 The only thing I am missing is exercise for our students.

Thank you @jardabezdek 🙏 
Yes I did not include any exercise for two reasons: I did not come up with anything interesting 😄  And the second is that I want our students to have more time to focus on the final project since they have only last two weeks for it.

**Pull request merged**
